# Generated by Django 2.2.3 on 2019-07-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediafile', models.FileField(upload_to='Life/media')),
                ('filetype', models.CharField(max_length=50)),
                ('uploadbyemailid', models.CharField(max_length=50)),
                ('uploadbyadminoruser', models.CharField(max_length=10)),
                ('uploaddate', models.DateField()),
                ('topicname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='MediaFiles',
        ),
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
