# Generated by Django 2.2.3 on 2019-07-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0003_auto_20190724_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaFile',
            new_name='MediaFiles',
        ),
    ]
