# Generated by Django 2.2.3 on 2019-07-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0005_auto_20190726_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafiles',
            name='mediafile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
