# Generated by Django 2.2.3 on 2019-07-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0007_auto_20190726_1002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaFile',
            new_name='MediaFiles',
        ),
    ]
