# Generated by Django 2.2.3 on 2019-07-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0008_auto_20190726_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaid', models.CharField(max_length=50)),
                ('commentbyemailid', models.CharField(max_length=50)),
                ('commentdate', models.DateField()),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediaLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaid', models.CharField(max_length=50)),
                ('likebyemailid', models.CharField(max_length=50)),
                ('likedate', models.DateField()),
            ],
        ),
    ]
