# Generated by Django 2.2.3 on 2019-07-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0009_mediacomments_medialikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafiles',
            old_name='commentsscount',
            new_name='commentscount',
        ),
    ]
