# Generated by Django 2.2.3 on 2019-08-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0010_auto_20190727_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaComments',
        ),
        migrations.RemoveField(
            model_name='mediafiles',
            name='commentscount',
        ),
    ]
