# Generated by Django 2.2.3 on 2019-08-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0012_auto_20190808_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('emailid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='')),
                ('userstatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='MediaFile',
            new_name='MediaFiles',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
