# Generated by Django 2.2.3 on 2019-08-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0013_auto_20190808_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsheading', models.CharField(max_length=500)),
                ('newsdescription', models.CharField(max_length=5000)),
                ('imagefile', models.FileField(upload_to='')),
                ('videofile', models.FileField(upload_to='')),
                ('newsstatus', models.CharField(max_length=50)),
            ],
        ),
    ]
