# Generated by Django 2.2.3 on 2019-08-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0014_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LifeTopic',
        ),
    ]
