# Generated by Django 2.2.3 on 2019-08-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0016_auto_20190812_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='picture',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
    ]
